google/generative-ai-docs

site/en/tools/notebook_magic.ipynb
Seems like these are required too. Tested on [this branch](https://github.com/google/generative-ai-docs/blob/nbfmt/site/en/tools/notebook_magic.ipynb)
Change-Id: If920556be8310dfdd28c8e206445a2a83dbb0f9e
=> Add execution_counts to execute_result outputs

site/en/tools/notebook_magic.ipynb
I think I ticked a box when saving from colab that added this. It's not a big deal, but it does point to my personal fork 😬
Also ran `nbfmt`, and fixed the "auth with sheets" step so that it is a closed form.
=> Remove `open in colab` icon

.github/workflows/notebooks.yml
This check was including the MakerSuite template notebooks, which are out of scope for the nblint/nbfmt checks.
=> Only check website notebooks

site/en/tutorials/chat_quickstart.ipynb, site/en/tutorials/embeddings_quickstart.ipynb, site/en/tutorials/text_quickstart.ipynb
These are the last remaining docs to fix titles so they're consistent across the quickstarts, and so they don't all show up the same in search results (either on-site or in the various engines).
I also found a weird broken markdown link, so fixed that too.
BUG=279128973
=> Consolidate titles in Python quickstart notebooks

templates/makersuite_text_prompt.ipynb
Reverts google/generative-ai-docs#43
This adds back in the code initially submitted in google/generative-ai-docs#42 now that the MakerSuite issue is fixed.
=> Revert "Revert "add safety settings to makersuite_text_prompt.ipynb""

.github/header-checker-lint.yml
This adds a lint check (via the already-installed app [license-header-lint-gcf](https://github.com/apps/license-header-lint-gcf)) that should require new files to have an appropriate license header, like the cross tool.
This is redundant for notebooks, so I haven't added them to this list.
=> Add license header lint

templates/makersuite_chat_prompt.ipynb
The final message to send to the model is now included in the messages array sent through URL parameters, removing the need for this code.
This should not be submitted until Wednesday June 14th ~1PM when the next update of MakerSuite happens, to coincide with the code changes on that side that change the URL parameters sent to this notebook.
=> Remove unneeded extra message from template

demos/palm/web/travel-planner/src/apis/LLMCaller.js
Problem: PaLM API URL and endpoint was out of date as of June 17th 2023. 
Fix: Updated PALM URL and API endpoints to `generativelanguage.googleapis.com` and `v1beta2` as per https://developers.generativeai.google/guide/palm_api_overview
=> Update LLMCaller.js to Preview URL and v1beta2 endpoint

demos/palm/web/mood-food/src/apis/llmCaller.js, demos/palm/web/talking-character/src/context/constants.ts
A couple of bug reports have come through for the demos referencing staging access issues (e.g. https://github.com/google/generative-ai-docs/issues/74 and https://github.com/google/generative-ai-docs/issues/73). These two references were all I could find that used non-prod API services. They also use `v1beta1`, but IIUC, that should still work for now.
=> Use prod URLs in mood-food and talking-character.

templates/makersuite_chat_prompt.ipynb, templates/makersuite_text_prompt.ipynb
Users have reported that the b64 encoded args are confusing, so hint that they can inspect them in Colab by pretty-printing the API args.
=> Print API args before executing.

.github/workflows/stale.yml
Adding github action workflow to mark stale issues and prs. This stale management workflow will add stale label and post reminder message after 14 days of inactivity and further close issue/pr after another 14 days of inactivity. We can also override stale action by adding override-stale label. Thanks! cc @google/gtech-llm-support
=> Adding github action workflow to mark stale issues and prs

.github/labeler.yml
Add auto-tag for Doc Agent.
Will rename other tags to `demo:*` and update this config in a later PR to better align to current directory structure.
Choose one: Other
=> Add auto-tag for Doc Agent

demos/palm/python/docs-agent/README.md, demos/palm/python/docs-agent/chatbot/templates/chatui/result.html, demos/palm/python/docs-agent/chroma.py, demos/palm/python/docs-agent/poetry.lock, demos/palm/python/docs-agent/pyproject.toml, demos/palm/python/docs-agent/scripts/markdown_to_plain_text.py, demos/palm/python/docs-agent/scripts/populate_vector_database.py, demos/palm/python/docs-agent/scripts/test_vector_database.py
- Updated the version of ChromaDB to 4.13.
- Re-generated the `poetry.lock` file.
- Updated Python scripts to migrate ChromaDB from 3.21 to 4.13 (See https://docs.trychroma.com/migration).
- Updated README to clarify when to delete an existing vector database.
- Updated the chatbot UI template to use "PaLM" to refer to the AI model.
This patch was created mainly to set the version of ChromaDB to the latest version (that is, 4.13). This should help resolve all the dependencies issues detected by Dependabot.
Choose one: Other (Dependencies updates)
=> [Docs Agent][Updates] Version 0.1.1

site/en/examples/clustering_with_embeddings.ipynb
The `embeddings-gecko-001` model doesn't seem to like anything over 10k, so filter them out in the tutorial.
Bugfix
=> Limit embedding requests to text samples under 10k

demos/palm/node/pipet-code-agent/.vscode/extensions.json, demos/palm/node/pipet-code-agent/.vscode/launch.json, demos/palm/node/pipet-code-agent/.vscode/settings.json, demos/palm/node/pipet-code-agent/.vscode/tasks.json
Turns out we were excluding `.vscode` directories in the project's top-level `.gitignore` file, so remove that an add the missing files.
Bugfix
=> Add missing `.vscode/` dir for Pipet.

examples/palm/python/google_cloud_functions/main.py
This illustrates how to use Cloud Functions with the PaLM API.
As the default service account is un-scoped, there is an extra step required to work with the API. This script can be dropped in to a GCF editor to get the service account authorised against the PaLM API.
A couple of users have gotten stuck doing this, so I figured we should drop a reference in here. If we don't want it in this repo I can dump it in a gist.
Choose one: Other
=> Add a sample Google Cloud Function script

examples/gemini/python/vectordb_with_chroma/vectordb_with_chroma.ipynb
So we don't break links (e.g. via colab) this should be merged in sync with cl/591176318.
=> Move the Chroma guide out of site/, into examples/

.github/workflows/notebooks.yml
Since we are also hosting docs on GitHub and linking out from the site, we want to lint these too. Also adds a bare-bones lint for templates (just copyright & license).
I did [some testing](https://github.com/markmcd/generative-ai-docs/actions?query=branch%3Anblint-ghdocs) over on a PR in my fork.
=> Lint non-website notebooks

examples/gemini/javascript/langchain_quickstart_node/README.md, examples/gemini/javascript/langchain_quickstart_node/main.js, examples/gemini/javascript/langchain_quickstart_node/package-lock.json
Adding one more example to the LangChain.js node quickstart: Embedding text.
This is a common use case and belongs in the quickstart.
Choose one: (Bug fix | Feature request | Documentation | Other): Feature request
- [ x] I have performed a self-review of my code.
- [ x] I have added detailed comments to my code where applicable.
- [ x] I have verified that my change does not break existing code.
- [ x] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ x] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [ x] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor …
=> added embedding example

site/en/gemma/docs/lit_gemma.ipynb
Fixing pip install instructions to use appropriate order as per https://keras.io/getting_started/#installing-keras-3
=> Update pip install instructions for keras and keras-nlp

site/en/docs/search_reranking_using_embeddings.ipynb
When published it looks like it could be talking about our package, so I've reworded the note such that it is clear while keeping the references intact.
=> Clarify wikipedia note in reranking guide

site/en/gemma/docs/jax_finetune.ipynb, site/en/gemma/docs/jax_inference.ipynb
@pcoet @markmcd @MarkDaoust PTAL
- In Fine-tuning notebook - under "Learn more" -> use "modules" instead of "methods".
- Add a link to [`gemma.params.load_and_format`](https://github.com/google-deepmind/gemma/blob/c6bd156c246530e1620a7c62de98542a377e3934/gemma/params.py#L27).
- Add a missing number ("2. Set environment variables") in the "Setup" section.
- Gemma `transformer` -> Gemma `Transformer` (class).
- Fix a missing `)`.
=> Minor tweaks to JAX Gemma docs

examples/gemini/python/docs-agent/README.md, examples/gemini/python/docs-agent/docs_agent/interfaces/README.md
Clean up Docs Agent's README.md files.
Clean up Docs Agent's README.md files.
- [ X] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ X] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).
=> [docs-agent] Clean up Docs Agent's README.md files.

site/en/gemma/docs/get_started.ipynb
Reversed the order of two steps in the Gemma quickstart: you need to set the backend before importing packages.
If you don't set the backend env var first, the backend choice won't take effect.
Bug fix
=> reverse order of import and backend steps

demos/palm/node/pipet-code-agent/README.md, demos/palm/node/pipet-code-agent/package-lock.json, demos/palm/node/pipet-code-agent/package.json, demos/palm/node/pipet-code-agent/src/comments.ts, demos/palm/node/pipet-code-agent/src/review.ts
Includes:
* "Add comment" and "review code" commands
* Move to `@google/generative-ai` SDK
* Replace extension preferences, so `google.palm.*` becomes `google.gemini.*`
* Update default model name to `models/gemini-1.0-pro-latest`
* Update README to point to content on [ai.google.dev](https://ai.google.dev/).
Tested both commands still work. Didn't test much beyond the happy case.
The app still lives in the /palm/ dir but we can move that in a follow-up PR, including a README that points back to the PaLM version at [`13372ab`](https://github.com/google/generative-ai-docs/tree/13372abed0d20571306b6b53121c2dd5a47ccb53/demos/palm/node/pipet-code-agent).
=> Migrate Pipet to use Gemini API

site/en/gemini-api/docs/semantic_retrieval.ipynb, site/en/tutorials/prompting_with_media.ipynb
These are needed so that we don't try and execute them on import.
=> Add outputs to site notebooks.

site/en/gemini-api/docs/model-tuning/python.ipynb, site/en/palm_docs/tuning_quickstart_python.ipynb
Looks like these slipped through the cracks.
Also updated to point to the new path.
=> Replace staging links with prod

site/en/gemini-api/docs/model-tuning/rest.ipynb, site/en/gemini-api/docs/semantic_retrieval.ipynb
Links were broken. Now they're not.
A couple of these were relative paths that were moved, but there were some instances of links using Colab's `scrollTo` notation, which doesn't work outside of Colab.
=> Fix broken links in notebooks

site/en/gemini-api/docs/prompting_with_media.ipynb
Fixed Colab and GitHub self links.
=> fixed Colab and GitHub links in prompting tutorial

site/en/gemini-api/docs/prompting_with_media.ipynb
=> Updates to Prompting with Media notebook

site/en/gemini-api/docs/semantic_retrieval.ipynb
=> Fix broken links in semantic_retrieval.ipynb

examples/gemini/python/vectordb_with_chroma/vectordb_with_chroma.ipynb, site/en/docs/react_gemini_prompting.ipynb, site/en/examples/chat_calculator.ipynb, site/en/examples/text_calculator.ipynb, site/en/gemini-api/tutorials/anomaly_detection.ipynb, site/en/gemini-api/tutorials/clustering_with_embeddings.ipynb, site/en/gemini-api/tutorials/document_search.ipynb, site/en/gemini-api/tutorials/text_classifier_embeddings.ipynb
The package name `google-generativeai` was written as `google.generativeai` which is incorrect.
Use the correct package name on the pip install command.
=> Normalize the Python package name to "google-generativeai"

site/en/gemini-api/tutorials/clustering_with_embeddings.ipynb, site/en/gemini-api/tutorials/document_search.ipynb, site/en/gemini-api/tutorials/text_classifier_embeddings.ipynb
Update links to examples for other Embeddings Tutorials
Previous links went nowhere
Bug fix
=> Update links to examples for other Embeddings Tutorials

site/en/gemini-api/tutorials/extract_structured_data.ipynb
Updated [tutorial](https://ai.google.dev/gemini-api/tutorials/extract_structured_data)
Typo fix
Choose one: (Bug fix)
=> Fixed "model = model = model" typo in tutorial

examples/gemini/python/api/generatecontent_text.py, examples/gemini/rest/api/generatecontent_text.sh
This sets up new directories for API samples and adds a full-file sample for both Python and REST/curl.
=> Add `generateContent` text samples for Python and rest

site/en/gemini-api/docs/vision.ipynb
Adding paragraphs on bounding box coordinate conversions to match main doc changes.
Added experts' explanation of conversion calculations.
Documentation
=> Adding notes on coordinate conversion to match main docs.

site/en/gemma/docs/gemma_chat.ipynb
Gemma chat notebook update: add Gemma 2 model info
Launch of Gemma 2 models
- [x ] I have performed a self-review of my code.
- [x ] I have added detailed comments to my code where applicable.
- [x ] I have verified that my change does not break existing code.
- [x ] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [x ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [x ] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).
=> Gemma chat notebook update: add Gemma 2 model info

site/en/gemma/docs/pytorch_gemma.ipynb
Update the PyTorch inference notebook to use Gemma 2 2B instead of Gemma 1.x.
Gemma 2 2B launch.
Documentation
=> update pytorch_gemma.ipynb to use gemma 2

site/en/responsible/docs/safeguards/shieldgemma_on_huggingface.ipynb, site/en/responsible/docs/safeguards/shieldgemma_on_keras.ipynb
Adds Colab notebooks demonstrating ShieldGemma's use in KerasNLP and Hugging Face Transformers.
Adds the Colab notebooks that document example usage of ShieldGemma. See launch announcement: https://developers.googleblog.com/en/smaller-safer-more-transparent-advancing-responsible-ai-with-gemma/
- [ x My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
=> Add ShieldGemma notebooks

site/en/gemma/docs/agile_classifiers.ipynb, site/en/gemma/docs/codegemma/code_assist_keras.ipynb, site/en/gemma/docs/codegemma/codegemma_flax_inference.ipynb, site/en/gemma/docs/codegemma/keras_quickstart.ipynb, site/en/gemma/docs/distributed_tuning.ipynb, site/en/gemma/docs/gemma_chat.ipynb, site/en/gemma/docs/integrations/langchain.ipynb, site/en/gemma/docs/jax_finetune.ipynb, site/en/gemma/docs/jax_inference.ipynb, site/en/gemma/docs/keras_inference.ipynb, site/en/gemma/docs/lit_gemma.ipynb, site/en/gemma/docs/lora_tuning.ipynb, site/en/gemma/docs/paligemma/fine-tuning-paligemma.ipynb, site/en/gemma/docs/paligemma/inference-with-keras.ipynb, site/en/gemma/docs/pytorch_gemma.ipynb, site/en/gemma/docs/recurrentgemma/recurrentgemma_jax_finetune.ipynb, site/en/gemma/docs/recurrentgemma/recurrentgemma_jax_inference.ipynb
This is a bit fragile, but it's only a temp measure until the CSS is included in the site bundle.
=> Add gemma.css to site notebooks.

site/en/gemma/docs/lora_tuning.ipynb
- prospective fix for translation serving failure
"external" link tagging is suspected cause of translation serving failure
=> Removing "external" link tags

examples/gemini/javascript/langchain_quickstart_node/main.js, site/en/gemini-api/docs/get-started/rest.ipynb
Minor improvements (wording, moving embeddings in the advance section...) as per PM feedback
To make the tutorial easier to understand by newcomers
Documentation
=> Python tutorial improvements (SBM feedback)

examples/gemini/python/docs-agent/README.md, examples/gemini/python/docs-agent/docs_agent/preprocess/splitters/markdown_splitter.py, examples/gemini/python/docs-agent/tasks/extract-workflows-task.yaml, examples/gemini/python/docs-agent/tasks/release-notes-task.yaml
- Prevent the AQA model from failing when its response's metadata returns entries containing an empty string.
- Update the `DraftReleaseNotes` tasks with polished prompts.
- Add a task file example to the main `README.md` file.
- Minor update in the `ExtractWorkflows` task to remove extra spaces.
Bug fix mainly
Choose one: (Bug fix)
- [ X] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ X] I have read through the …
=> [Docs Agent] Bug fix: Prevent the AQA model from failing when a response returns entries containing a null string

examples/gemini/python/docs-agent/docs/create-a-new-task.md, examples/gemini/python/docs-agent/docs_agent/utilities/tasks.py, examples/gemini/python/docs-agent/pyproject.toml
What's changed:
- **New how-to guide**: Publish a new how-to guide on creating a new task.
- **Add response type flag**: Add a new flag that allows users to specify the response type of `agent runtask`.
A minor release that mainly includes a new how-to guide on creating a new task.
Documentation update.
- [ X] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ X] I have read through the …
=> [Docs Agent] Docs Agent release version 0.4.1

examples/gemini/python/docs-agent/README.md
Updated Docs Agent's main README.md file to bring the changes missed in its 0.4.1 update.
The previous 0.4.1 release didn't end up including the changes in Docs Agent's README.md.
- [ X] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ X] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License …
=> [Docs Agent] Update Docs Agent's README.md file, which was missed its 0.4.1 update.

demos/palm/web/quick-prompt/src/store.js, demos/palm/web/talking-character/src/apis/textToSpeech.ts, demos/palm/web/talking-character/third_party/mediapipe/web/graph_runner/graph_runner.ts, demos/palm/web/textfx/src/components/generic/outputCard/outputCard.tsx, demos/palm/web/textfx/src/components/generic/outputSection/outputSection.module.scss
=> Fixed Typo in multiple files

site/en/gemini-api/docs/vision.ipynb
Updated the vision notebook so that it reflects the updated [vision docs](https://ai.google.dev/gemini-api/docs/vision?lang=python). Specifically, the structure of the doc and how to prompt with base64 encoded images.
Want to make sure developers are able to run the examples from the updated docs right away.
Feature request / documentation
=> Update vision notebook to align with updated vision docs

site/en/gemma/docs/paligemma/fine-tuning-paligemma.ipynb, site/en/gemma/docs/paligemma/inference-with-keras.ipynb
Updating PaliGemma notebooks
Choose one: (Documentation )
=> Updating PaliGemma notebooks

site/en/gemma/docs/paligemma/inference-with-keras.ipynb
**Typo:** Fixed the model name in the code - `paligemma = keras_hub.models.PaliGemmaCausalLM.from_preset("paligemma_3b_mix_224")` from "paligemma_3b_mix_224" to "pali_gemma_3b_mix_224" to correctly load the model.
**Broken Link:** Updated the URL for "PaliGemma prompt and system instructions" by replacing the existing URL with the correct URL - https://ai.google.dev/gemma/docs/paligemma/prompt-system-instructions/##prompt_task_syntax.
Choose one: (Bug fix)
=> PaliGemma model Code Correction: Model Name & Documentation Link

site/en/gemini-api/docs/vision.ipynb
Fixed the typo mistake at code `Markdown(esponse.text)` in the  'Transcribe video and provide visual descriptions' section in 'vision' doc which gives `NameError: name 'esponse' is not defined` while code exceution.
Fixed the typo by adding 'r' in code `Markdown(response.text)`.
=> Update vision.ipynb by fixing the typo in code

site/en/gemma/docs/paligemma/inference-with-keras.ipynb
Update PaliGemma inference notebook to use PaliGemma 2 Mix model.
Part of PaliGemma 2 Mix launch
Bug fix
=> update paligemma 2

examples/gemini/node/flutter_theme_agent/src/theme.ts, examples/gemini/python/docs-agent/docs_agent/interfaces/chatbot/chatui.py, examples/gemini/python/docs-agent/docs_agent/interfaces/cli/cli_helpme.py, examples/gemini/python/docs-agent/pylintrc
=> Update Typos in Multiple files 

site/en/responsible/docs/safeguards/shieldgemma2_on_huggingface.ipynb
Adds a Colab Notebook describing how to use the newly released ShieldGemma 2 model for image content moderation, part of Google's Responsible Generative AI Toolkit.
Documents the expanded ShieldGemma family of models supporting text and image content moderation needs of GEnAI application developers. 
=> Adding ShieldGemma 2 notebook to Responsible AI Toolkit docs

site/en/gemma/docs/core/huggingface_inference.ipynb
The current url to the transformers doc is broken
=> Fix broken link in transformers guide

site/en/gemma/docs/core/huggingface_inference.ipynb
The audio section of the HF Transformers inference notebook referred to images erroneously instead of audio files.
It was inaccurate to say "images" there.
Documentation
- [-] I have added detailed comments to my code where applicable.
=> Notebook update for Gemma 3n on HF - fix typo

site/en/gemma/docs/core/pytorch_gemma.ipynb
Fixes:
* Hanging `<td>` tag in the links table
* Incorrect derivation of `CONFIG` from `VARIANT` 
* Incorrect argument passed to `get_model_config()`
* Common typo: "an PyTorch" should be "a PyTorch"
Bug reported in https://github.com/google/gemma_pytorch/issues/81 and tracked as http://b/419461706 internally.
=> Fixing Gemma PyTorch docs

site/en/gemma/docs/codegemma/keras_quickstart.ipynb
Update keras-nlp to keras-hub which is the latest package
=> Update keras-nlp to keras-hub
