google/generative-ai-docs

demos/palm/web/talking-character/src/apis/mediapipe_audio_blendshapes.ts

remove old comments

---

site/en/tutorials/text_quickstart.ipynb

and regenerate outputs.
b/283100526

Add a example using stop_sequences

---

site/en/tools/notebook_magic.ipynb

We made some manual tweaks to this pre-I/O that weren't run e2e, so this gets things back in sync.
I've also turned down the French on the few-shot compiled example so that it still works with the language filter.

Re-run magic notebook to ensure outputs are correct

---

site/en/examples/clustering_with_embeddings.ipynb
site/en/examples/doc_search_emb.ipynb
site/en/examples/train_text_classifier_embeddings.ipynb
site/en/examples/vectordb_with_chroma.ipynb
site/en/tools/notebook_magic.ipynb
site/en/tutorials/chat_quickstart.ipynb
site/en/tutorials/embeddings_quickstart.ipynb
site/en/tutorials/text_quickstart.ipynb

Add a link to the palm site.

---

.github/workflows/notebooks.yml

Tested on my fork, with some manual modifications to notebooks. See [this run](https://github.com/markmcd/generative-ai-docs/actions/runs/5044070769/jobs/9046647863?pr=3).

Add Notebook lint/fmt actions

---

templates/makersuite_text_prompt.ipynb

parses safety settings from URL params and passes it to the palm API

add safety settings to makersuite_text_prompt.ipynb

---

templates/makersuite_text_prompt.ipynb

Reverts google/generative-ai-docs#42

Revert "add safety settings to makersuite_text_prompt.ipynb"

---

demos/palm/web/talking-character/README.md

Adding API_KEYs Setting instructions in README.md to help beginner setting the project clearly.

Talking Character: add API_KEYs Setting instructions in README.md

---

demos/palm/python/docs-agent/README.md

fixed bug in documentation which was causing a issue while running the Docs Agent chat app.
this bug was causing me issue https://github.com/google/generative-ai-docs/issues/176 and I added a extra line in documentation which solves this issue and @nickvander suggested me to fix this in documentation.
Documentation

fixed documentation for docs-agent demo

---

site/en/docs/semantic_retriever.ipynb
site/en/examples/anomaly_detection.ipynb
site/en/examples/chat_calculator.ipynb
site/en/examples/clustering_with_embeddings.ipynb
site/en/examples/doc_search_emb.ipynb
site/en/examples/text_calculator.ipynb
site/en/examples/train_text_classifier_embeddings.ipynb
site/en/examples/vectordb_with_chroma.ipynb
site/en/palm_docs/chat_node_quickstart.ipynb
site/en/palm_docs/chat_quickstart.ipynb
site/en/palm_docs/curl_quickstart.ipynb
site/en/palm_docs/embeddings_quickstart.ipynb
site/en/palm_docs/notebook_magic.ipynb
site/en/palm_docs/text_node_quickstart.ipynb
site/en/palm_docs/text_quickstart.ipynb
site/en/palm_docs/tuning_quickstart_python.ipynb
site/en/palm_docs/tuning_quickstart_rest.ipynb
site/en/tutorials/rest_quickstart.ipynb

Mainly to update the img URLs for the new domain. Also includes latest content.

Sync notebook content

---

templates/aistudio_gemini_prompt_chat_b64.ipynb
templates/aistudio_gemini_prompt_freeform_b64.ipynb

Remove keys

---

templates/aistudio_gemini_prompt_chat_b64.ipynb
templates/aistudio_gemini_prompt_freeform_b64.ipynb

Add _b64 to base64 variable names

---

site/en/docs/semantic_retriever.ipynb
site/en/examples/doc_search_emb.ipynb

Last piper revision: 595501423

Sync notebooks.

---

site/en/tutorials/function_calling_python_quickstart.ipynb

Add a notebook with an example of basic function calling.

Add basic function calling example notebook.

---

.gitignore
examples/gemini/javascript/langchain_quickstart_node/.gitignore
examples/gemini/javascript/langchain_quickstart_node/README.md
examples/gemini/javascript/langchain_quickstart_node/main.js
examples/gemini/javascript/langchain_quickstart_node/package-lock.json
examples/gemini/javascript/langchain_quickstart_node/package.json

Added an example showing how to use Gemini models with LangChain.js in Node.js.
LangChain is a popular framework for developing LLM apps. This quickstart is a runnable example that illustrates some of the functionality discussed in the existing LangChain.js docs:
* [LangChain.js: Google](https://js.langchain.com/docs/integrations/platforms/google)
* [LangChain.js: ChatGoogleGenerativeAI](https://js.langchain.com/docs/integrations/chat/google_generativeai)
Note: Eventually I'd like to add a TypeScript version of this example, and perhaps also a web version. I might also add a small server implementation to make it a more typical Node app.
Choose one: (Bug fix | Feature request | Documentation | Other): Other (example)

Added an example showing how to use Gemini with LangChain.js in Node

---

DEMO_MAINTAINERS.md

As mentioned in the [demo maintainer doc](https://github.com/google/generative-ai-docs/blob/main/DEMO_MAINTAINERS.md), I would like to take the responsibility to be a maintainer of travel-planner . I have red the Contributing guide and signed the CLA as well
I am very excited about the advancements in Google-Gemini and would like to gain in-depth knowledge about it. What could be even better is getting a project to maintain, as it would exponentially enhance my skills
Other

docs:proposal to be demo maintainer- TRAVEL-PLANNER

---

DEMO_MAINTAINERS.md

As mentioned in the [DEMO_MAINTAINERS.md](https://github.com/google/generative-ai-docs/blob/main/DEMO_MAINTAINERS.md), I've thoroughly reviewed the project's contribution guidelines and have already signed the CLA, demonstrating my commitment to responsible participation.
The groundbreaking progress in Google-Gemini has truly ignited my passion for large language models. I'm eager to delve deeper and contribute to this transformative technology, not just for personal skill development, but to be part of something that has the potential to shape the future.
Other

docs: proposal to be demo maintainer - LIST IT

---

site/en/docs/semantic_retriever.ipynb
site/en/examples/anomaly_detection.ipynb
site/en/examples/chat_calculator.ipynb
site/en/examples/clustering_with_embeddings.ipynb
site/en/examples/doc_search_emb.ipynb
site/en/examples/text_calculator.ipynb
site/en/examples/train_text_classifier_embeddings.ipynb
site/en/palm_docs/chat_node_quickstart.ipynb
site/en/palm_docs/chat_quickstart.ipynb
site/en/palm_docs/curl_quickstart.ipynb
site/en/palm_docs/embeddings_quickstart.ipynb
site/en/palm_docs/notebook_magic.ipynb
site/en/palm_docs/text_node_quickstart.ipynb
site/en/palm_docs/text_quickstart.ipynb
site/en/palm_docs/tuning_quickstart_python.ipynb
site/en/palm_docs/tuning_quickstart_rest.ipynb
site/en/tutorials/function_calling_python_quickstart.ipynb
site/en/tutorials/rest_quickstart.ipynb

Replace view-on text

---

site/en/gemma/docs/distributed_tuning.ipynb

Update Kaggle link in distributed_tuning.ipynb

---

site/en/docs/semantic_retriever.ipynb
site/en/examples/anomaly_detection.ipynb
site/en/examples/clustering_with_embeddings.ipynb
site/en/examples/doc_search_emb.ipynb
site/en/examples/text_calculator.ipynb
site/en/examples/train_text_classifier_embeddings.ipynb
site/en/gemma/docs/distributed_tuning.ipynb
site/en/gemma/docs/get_started.ipynb
site/en/tutorials/function_calling_python_quickstart.ipynb
site/en/tutorials/rest_quickstart.ipynb

Having these on the GitHub notebook copies should mean we can treat them as a SoT now. I'll test with a d2d run once merged.

Add keywords and image_path metadata to notebooks.

---

site/en/gemma/docs/agile_classifiers.ipynb
site/en/gemma/docs/distributed_tuning.ipynb
site/en/gemma/docs/get_started.ipynb
site/en/gemma/docs/lora_tuning.ipynb

Sync docs from Google3 to GitHub

---

site/en/gemma/docs/jax_finetune.ipynb
site/en/gemma/docs/jax_inference.ipynb

Add JAX Gemma docs

---

site/en/tutorials/function_calling_python_quickstart.ipynb

Replay #281

---

site/en/gemma/docs/get_started.ipynb

Made minor fixes to Keras + Gemma get started. Need to sync.
- [x ] I have performed a self-review of my code.
- [x ] I have added detailed comments to my code where applicable.
- [x ] I have verified that my change does not break existing code.
- [x ] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [x ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [x ] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

syncing changes to Keras + Gemma get started

---

site/en/docs/react_gemini_prompting.ipynb

Minor changes - mostly simplifying or clarifying text.

Clean up some prose to align with style guide

---

site/en/tutorials/tuning_quickstart_rest.ipynb

Add tuning Quickstart for REST API

---

site/en/gemma/docs/integrations/langchain.ipynb

Adding langchain + gemma tutorial.
Request for Gemma + LangChain tutorial.
- [ x] I have performed a self-review of my code.
- [ x] I have added detailed comments to my code where applicable.
- [ x] I have verified that my change does not break existing code.
- [ x] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ x] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [ x] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

adding gemma + langchain tutorial

---

examples/gemini/python/langchain/Gemini_LangChain_QA_Pinecone_WebLoad.ipynb

Add an example for Gemini integration with LangChain and Pinecone
Other

Add an example for Gemini integration with LangChain and Pinecone

---

site/en/tutorials/quickstart_colab.ipynb

New quickstart Colab.
- [x ] I have performed a self-review of my code.
- [ x] I have added detailed comments to my code where applicable.
- [x ] I have verified that my change does not break existing code.
- [x ] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [x ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [x ] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

adding new Gemini quickstart Colab

---

site/en/tutorials/quickstart_colab.ipynb

add links to quickstart

---

site/en/tutorials/quickstart_colab.ipynb

- [x ] I have performed a self-review of my code.
- [x ] I have added detailed comments to my code where applicable.
- [x ] I have verified that my change does not break existing code.
- [x ] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [x ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [x ] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

Add output to Gemini API quickstart Colab

---

CODEOWNERS

Update CODEOWNERS for docs-agent

---

site/en/tutorials/rest_quickstart.ipynb

Use alt=sse so stream results are parseable.
Use GOOGLE_API_KEY.

Fix streaming example

---

site/en/gemma/docs/codegemma/code_assist_keras.ipynb
site/en/gemma/docs/codegemma/keras_quickstart.ipynb

Syncing codegemma notebooks

---

site/en/tutorials/prompting_with_media.ipynb

Syncing notebooks

---

site/en/tutorials/structured_data_extraction.ipynb

Wait until this is supported in the SDK before subitting.

Use tool_config and response_mime_type

---

CODEOWNERS

Adding AIS team as owners for the AIS templates.

Update CODEOWNERS for templates

---

site/en/gemini-api/docs/model-tuning/python.ipynb

updated links and display name for model tuning notebook

---

examples/gemini/python/vectordb_with_chroma/vectordb_with_chroma.ipynb
site/en/gemini-api/tutorials/document_search.ipynb
site/en/gemini-api/tutorials/text_classifier_embeddings.ipynb

update python quickstart links

---

site/en/gemini-api/tutorials/extract_structured_data.ipynb

I've improved the schema generation code in https://github.com/google-gemini/generative-ai-python/pull/309
Will merge before next release.

Auto schema

---

site/en/gemini-api/docs/function-calling/python.ipynb
site/en/gemini-api/docs/prompting_with_media.ipynb

updating docs for video and parallel function calling

---

site/en/gemma/docs/paligemma/fine-tuning-paligemma.ipynb

- for: ai.google.dev/gemma/docs/paligemma/fine-tuning-paligemma
Adding PaliGemma notebook for colab integration
Integration with PallGemma docs page: 
https://ai.google.dev/gemma/docs/paligemma/fine-tuning-paligemma
Choose one: Documentation | Other)

Upload PaliGemma JAX tuning notebook

---

site/en/gemini-api/tutorials/anomaly_detection.ipynb

Fixed a typo
Fixed a typo
Just a typo fix
Bug fix

Update anomaly_detection.ipynb - fixed typo

---

site/en/gemini-api/docs/model-tuning/rest.ipynb

Fixed spelling error in documentation
Change was required because it might confuse someone else reading the documentation
spelling error

Fixed docs spelling

---

site/en/gemini-api/docs/vision.ipynb

Uploading vision capabilities Colab as part of DevRel CY
Uploading executable Colab for vision capabilities guide (which is coming shortly).
Assigned the vision capabilities guide and wanted an executable Colab for demos
Documentation
- [X ] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ X] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed …

Uploading vision.ipynb as part of vision capabilities guide.

---

site/en/gemma/docs/gemma_chat.ipynb

Add the Gemma Chat notebook to GitHub
Fixes Issue #440

Add Gemma Chat notebook to GitHub

---

site/en/gemma/docs/recurrentgemma/recurrentgemma_jax_finetune.ipynb
site/en/gemma/docs/recurrentgemma/recurrentgemma_jax_inference.ipynb

Add RecurrentGemma JAX Flax notebooks

---

site/en/gemma/docs/gemma_chat.ipynb
site/en/gemma/docs/keras_inference.ipynb
site/en/gemma/docs/lora_tuning.ipynb

Update to Gemma 2
Update to Gemma 2

Update Gemma doc

---

site/en/gemma/docs/codegemma/codegemma_flax_inference.ipynb
site/en/gemma/docs/paligemma/fine-tuning-paligemma.ipynb
site/en/gemma/docs/recurrentgemma/recurrentgemma_jax_inference.ipynb

Add Flax CodeGemma Quickstart guide to CodeGemma docs. Added references to Flax in all Jax guides.

Add Flax CodeGemma Quickstart guide to CodeGemma docs.

---

site/en/gemma/docs/codegemma/code_assist_keras.ipynb

Potentially a cause of a downstream bug. Either way it fixes the HTML.

Add missing </td> to button block

---

site/en/gemma/docs/codegemma/keras_quickstart.ipynb

Should fix DevSite Machine Translation issues

Add missing </td> to table block

---

site/en/gemma/docs/codegemma/codegemma_flax_inference.ipynb
site/en/gemma/docs/paligemma/fine-tuning-paligemma.ipynb

This ensures notebook diffs are simple and consistent. Also fixed buttons on unformatted notebooks.

`nbfmt` gemma site notebooks

---

site/en/gemini-api/docs/model-tuning/python.ipynb

Remove note about tuning only being supported for 1.0.

---

site/en/docs/search_reranking_using_embeddings.ipynb

`esentially` -> `essentially`
Documentation

fix(docs): correct typo essentially in search_reranking_using_embeddings.ipynb

---

site/en/gemma/docs/core/keras_inference.ipynb
site/en/gemma/docs/core/lora_tuning.ipynb

Updating Keras notebooks to Gemma 3
keeping docs up to date with latest version

Updating Keras notebooks to Gemma 3

---

site/en/gemma/docs/core/huggingface_inference.ipynb

Add Hugging Face Inference guide notebook
Adding notebook copy in GitHub for Colab links

Add Hugging Face Inference guide notebook

---

site/en/gemma/docs/paligemma/inference-with-keras.ipynb

Nit, just updating the proper package name for keras-hub

update Keras hub package

---

site/en/gemma/docs/capabilities/vision/video-understanding.ipynb
site/en/gemma/docs/core/huggingface_inference.ipynb

Notebook updates for Gemma 3n
